"""empty message

Revision ID: 06251728b542
Revises: 685dcd0ed66d
Create Date: 2020-09-28 14:50:52.335727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06251728b542'
down_revision = '685dcd0ed66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_create_time'), 'message', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_create_time'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
