"""empty message

Revision ID: 685dcd0ed66d
Revises: 
Create Date: 2020-07-06 00:14:35.269655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685dcd0ed66d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=38), nullable=True),
    sa.Column('password_hash', sa.String(length=288), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('activation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
